spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
logging.level:
  org:
    hibernate:
      type:
        descriptor:
          sql:
            org.hibernate.type.descriptor.sql.BasicBinder: trace
    springframework:
      web.servlet: debug
cloud: # AWS IAM SecretKey ??
  s3:
    bucket: image-test-suyoung    # ex) marryting-gyunny
    dir: /image # ex) /gyunny
  region:
    static: ap-northeast-2
  stack:
    auto: false