spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
logging.level:
  org:
    hibernate:
      type:
        descriptor:
          sql:
            org.hibernate.type.descriptor.sql.BasicBinder: trace
    springframework:
      web.servlet: debug
discord:
  webhookUrl: https://discord.com/api/webhooks/1061335628605829240/LXxLolrz5XNyLg1mcEAz8O4jqFdVJnsDPkJt07gklBQIo8kU39BnZcBI6K1TIjf81wXB